export const WINNERS_TYPES = {
    GET_CONTEST_WINNERS_LOADING: "GET_CONTEST_WINNERS_LOADING",
    GET_CONTEST_WINNERS: "GET_CONTEST_WINNERS",
    RESET_CONTEST_WINNERS: "RESET_CONTEST_WINNERS",
    GET_CONTEST_WINNERS_FAIL: "GET_CONTEST_WINNERS_FAIL"
}