export const CONTESTS_TYPES = {
    GET_CONTESTS_INITIAL_STATE: "GET_CONTESTS_INITIAL_STATE",
    GET_CONTESTS: "GET_CONTESTS",
    GET_CONTESTS_LOADING: "GET_CONTESTS_LOADING",
    GET_CONTESTS_SUCCES: "GET_CONTESTS_SUCCESS",
    GET_CONTESTS_FAIL: "GET_CONTESTS_FAIL"
}