export const CONTESTS_TYPES = {
    GET_CONTESTS_INITIAL_STATE: "GET_CONTESTS_INITIAL_STATE",
    GET_CONTESTS: "GET_CONTESTS",
    APPEND_NEW_CONTEST: "APPEND_NEW_CONTEST",
    APPEND_TO_DRAFT: "APPEND_TO_DRAFT",
    APPEND_EDITED_CONTEST: "APPEND_EDITED_CONTEST",
    DELETE_FROM_DRAFT: "DELETE_FROM_DRAFT",
    GET_CONTESTS_LOADING: "GET_CONTESTS_LOADING",
    APPEND_EDITED_DRAFT: "APPEND_EDITED_DRAFT",
    APPEND_DONE_ACTION: "APPEND_DONE_ACTION",
    GET_CONTESTS_SUCCES: "GET_CONTESTS_SUCCESS",
    GET_CONTESTS_FAIL: "GET_CONTESTS_FAIL"
}