export  const loginType={
    SET_INITIAL_STATE:'SET_INITIAL_STATE',
  
    SET_EMAIL:"SET_EMAIL",
    SET_PASSWORD:"SET_PASSWORD",
    SET_LOGIN_ERROR:'SET_EMAIL_ERROR',
    SET_LOGIN_ERROR_MESSAGE:'SET_EMAIL_ERROR_MESSAGE',
    SET_REMEMBER_ME:'SET_REMEMBER_ME',
    LOGOUT: 'LOGOUT',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS'

}