export const ContestTypes={
    SET_NUM_WINNERS: 'SET_NUM_WINNERS',
    SET_PRIZES:'SET_PRIZES',
    SET_STATE: 'SET_STATE',
    ADD_ACTION: "ADD_ACTION",
    REMOVE_ACTION: "REMOVE_ACTION",
    UPDATE_ACTION: "UPDATE_ACTION"
}