export const ContestTypes={
    SET_PRIZES:'SET_PRIZES',
    REMOVE_PRIZE: 'REMOVE_PRIZE',
    SET_STATE: 'SET_STATE',
    ADD_ACTION: "ADD_ACTION",
    SET_WINNERS_NUM: "SET_WINNER_NUM",
    REMOVE_ACTION: "REMOVE_ACTION",
    UPDATE_ACTION: "UPDATE_ACTION",
    SET_DURATION: "SET_DURATION",
    CHECK_DATA: "CHECK_DATA",
    RESET_VALIDATION: "RESET_VALIDATION"
}